version: "3"
services:
  db:
    build: ./db
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
    image: database
  service:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
    ports:
      - "2022:2022"
      - "9229:9229"
